### ISSUE TITLE
support STM32L073CZ?

### ISSUE THREAD

**Issue by seydouniar** [ARMmbed/mbed-os-example-bootloader#101]
Hello,
I try to do the bootloader for my stm32L073CZ used the flash memory but i don't work. I want to know if it support the serie of stm32.
Cordially.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-877*

**Comment by 0xc0170** [comment]
What is the question? what is not working?

What target are you using? I can see only `NUCLEO_L073RZ` supported in Mbed OS but that does not have MCU stm32L073CZ?

**Comment by seydouniar** [comment]
> 
> 
> What is the question? what is not working?
> 
> What target are you using? I can see only `NUCLEO_L073RZ` supported in Mbed OS but that does not have MCU stm32L073CZ?

I use the custom_target on mbed to declare my micro. My question is to known if the mbed bootloader example must work with any MCU? I tried with NUCLEO_L073RZ but it have not a sd.
Cordially

**Comment by c1728p9** [comment]
Hi @seydouniar this example only works unmodified with the targets listed in [mbed_app.json](https://github.com/ARMmbed/mbed-os-example-bootloader/blob/master/mbed_app.json#L25-L40). Targets with `bootloader_supported` set to `true` in targets.json, [such as the LPC1768]( https://github.com/ARMmbed/mbed-os/blob/master/targets/targets.json#L3402), have bootloader support and can be easily be added to this example. Targets without this need changes to be made in mbed-os before bootloader builds can be used.

**Comment by cmonr** [comment]
Closing because this sounds like it's been answered.
