### ISSUE TITLE
What does the "Pad" means??

### ISSUE THREAD

**Issue by hjpark-sdt** [ARMmbed/mbed-os-example-bootloader#103]
### Description

Hi

I just try to be training for bootloder and have a question.
Like a title of this issue, I don't know what the "pad" means.
Additionally, what is the difference between `mbed-os-example-bootloader.bin` and `mbed-os-example-bootloader_application.bin` that made when bootloder project is built ?

Thanks.

### Issue request type

[x] Question  
[ ] Enhancement  
[ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-919*

**Comment by hjpark-sdt** [comment]
I can't open this link(https://jira.arm.com/browse/MBOCUSTRIA-919)...
Please confirm it.

**Comment by cmonr** [comment]
@heejungPark This is an internal-only link that we use to more easily track issues from multiple sources.

**Comment by c1728p9** [comment]
Hi @heejungPark in readme.md "pad" refers to filling unused space with some value so it is the correct size.  The difference between `mbed-os-example-bootloader.bin` and `mbed-os-example-bootloader_application.bin` is that `mbed-os-example-bootloader_application.bin` is not padded while `mbed-os-example-bootloader_application.bin` is padded. For example the size of two images may be:
 -  `mbed-os-example-bootloader_application.bin`:
    - Program size 0xEBE0
    - Total file size 0xEBE0
 - `mbed-os-example-bootloader.bin`:
    - Program size 0xEBE0
    - Pad '0xFF' of size 0x11420
    - Total file size 0xEBE0 +0x11420 = 0x20000

**Comment by hjpark-sdt** [comment]
Hi @c1728p9 

I understand about it.
Thanks for your answer.

**Comment by hjpark-sdt** [comment]
I have a last question.
I got a difference of format, but don't know a difference of functionality or usage.
Where are they used to?

Thanks.

**Comment by c1728p9** [comment]
Hi @heejungPark the different file formats supported are `.bin` and `.hex`. Even though data is stored in a different format these contain the same padding when building a bootloader.

**Comment by hjpark-sdt** [comment]
Thanks but I would miswrite the question.
(It is not the question about 'pad'.)
I wonder what each file, `mbed-os-example-bootloader_application.bin` and `mbed-os-example-bootloader.bin`, is used for?

Thanks.

**Comment by c1728p9** [comment]
Hi @heejungPark `mbed-os-example-bootloader_application.bin` is just a result of the build process. There is no particular use of it. The image you should load and use with your application is `mbed-os-example-bootloader.bin`.

**Comment by hjpark-sdt** [comment]
Oh, okay, I got it.
Thank you very much.
