### ISSUE TITLE
After build bootloader it doesn't generate needed files (padded and unpadded) 

### ISSUE THREAD

**Issue by pawelm87** [ARMmbed/mbed-os-example-bootloader#106]
### Description

After compilate bootloader I got two files bin:

- mbed-os-example-bootloader.bin - 121 KB
- mbed-os-example-bootloader_application.bin - 121 KB

Two file have this same size and (binary) looks that same.
When I used "mbed-os-example-bootloader_application.bin" to build application it doesn't work. Bootloader load app from SD, flashed memory, print message "Starting application" and stop. App don't start. The tutorial on the [github](https://github.com/armmbed/mbed-os-example-bootloader) website states that there should be two different files for the bootloader to work.

When I change folder "tools" (old version mbed-os probably 5.10.4) in mbed-os everything work fine, I got two file with difference size. App builded from file padded bootloader - start after flashing memory. 

> Compiler GCC_ARM
> STM32L476 - I changed mbed_app.json - bootloader works on mbed-os 5.10.4
> mbed-os 5.11.5 - imported program in 20.03.2019 from git
> program:
> - mbed-os-example-bootloader 
> - mbed-os-example-blinky
>
> in Mbed Studio change folder "tools" don't work 

Can you fix this bug or told what happens ??
Similar problem [https://github.com/ARMmbed/mbed-os/issues/9949](url)

### Issue request type

[ ] Question  
[ ] Enhancement  
[X] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-1041*

**Comment by pawelm87** [comment]
Somebody from mbed can tested bootloader and give me feedback ?

**Comment by c1728p9** [comment]
Hi @pawelm87 I gave this a try and can confirm this is a bug. As you mentioned it appears to be the same problem as https://github.com/ARMmbed/mbed-os/issues/9949. Padding broken in mbed-os version 5.11.1. If you use 5.11.0 it should work correctly.

@theotherjimmy @bridadan could one of you take a look at this?

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.

**Comment by adbridge** [comment]
Apologies, this was closed in error by the automated bot - re-opening.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-2067*

**Comment by 0xc0170** [comment]
I am closing this due to example being deprecated. The bug is still opened above.
