### ISSUE TITLE
What's the difference between this and `mbed-bootloader`?

### ISSUE THREAD

**Issue by andrewc-arm** [ARMmbed/mbed-os-example-bootloader#124]
### Description

Hi,
There seems to be two Mbed bootloader examples in ARMmbed.
This repo and [mbed-bootloader](https://github.com/ARMmbed/mbed-bootloader).
Could you kindly explain what are the differences?

### Issue request type

[X] Question  
[ ] Enhancement  
[ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/IOTSTOR-977*

**Comment by SeppoTakalo** [comment]
Mbed Bootloader is the bootloader that we use.

The 'example-bootloader' seems to be code that demonstrated how can you create a bootloader from scratch..

I think we should drop the former, as the Mbed bootloader is public and simple enough.

**Comment by andrewc-arm** [comment]
Thank you!
