### ISSUE TITLE
CMake build fails with `The source directory does not appear to contain CMakeLists.txt`

### ISSUE THREAD

**Issue by Patater** [ARMmbed/mbed-os-example-bootloader#147]
### Description of defect

```
[EXAMPLES]> INFO     In folder 'mbed-os-example-filesystem'
[EXAMPLES]> INFO     In folder 'mbed-os-example-mesh-minimal'
[EXAMPLES]> INFO     In folder 'mbed-os-example-bootloader'
[EXAMPLES]> INFO     Compiling mbed-os-example-bootloader K64F GCC_ARM
[EXAMPLES]> INFO     Executing command 'mbed-tools compile -t GCC_ARM -m K64F -c'...

#### STDOUT ####
Configuring project and generating build system...

#### STDERR ####
CMake Error: The source directory "/builds/workspace/mbed-os-ci_cmake-example-GCC_ARM-dev@4/examples/mbed-os-example-bootloader" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
ERROR: CMake invocation failed!

More information may be available by using the command line option '-v'.
```

#### Target(s) affected by this defect ?
K64F

#### Toolchain(s) (name and version) displaying this defect ?
GCC_ARM

#### What version of Mbed-os are you using (tag or sha) ?

9bbc8c914c7e 

#### What version(s) of tools are you using. List all that apply (E.g. mbed-cli)
Mbed CLI 2

#### How is this defect reproduced ?
`mbed-tools compile -t GCC_ARM -m K64F -c`

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-3791*

**Comment by 0xc0170** [comment]
This example shall be deprecated and not required to have CMake support as agreed previously.

@donatieng Please review . If agreed, I can add deprecated notes and request CI test removal with CMake.

**Comment by Patater** [comment]
Yes, agreed we'll deprecate this example.

**Comment by Patater** [comment]
Fixed by https://github.com/ARMmbed/mbed-os-example-bootloader/pull/148
