### ISSUE TITLE
 increase the support of other board

### ISSUE THREAD

**Issue by wjffsx** [ARMmbed/mbed-os-example-bootloader#2]
I would like to increase the support of DISCO_F407VG bootloader, how to modify the code?

**Comment by 0xc0170** [comment]
> I would like to increase the support of DISCO_F407VG bootloader, how to modify the code?

This target should provide implementation for flash HAL (this example is using flash API), plus have also new filesystem support (verify that it works). Does that answer your question?

**Comment by 0xc0170** [comment]
@wjffsx Please look at https://docs.mbed.com/docs/mbed-os-handbook/en/latest/advanced/flash/. I'll close this. you can create a question under mbed-os.
