### ISSUE TITLE
What are the options without an SD card? (OTA)

### ISSUE THREAD

**Issue by amq** [ARMmbed/mbed-os-example-bootloader#29]
I am looking for the best way to perform OTA updates with CoAP block-wise messages.

While I could probably do a similar thing as `apply_update()`, it would easily result in a corrupted flash in the case of a network or power loss.

Would it be reasonable to have 2 "partitions" and use something like https://github.com/ARMmbed/mbed-littlefs to first download and verify the firmware to the second partition, then reboot and have the bootloader boot from there, or at least read from there (like from an SD card) to flash the first partition?

Maybe https://github.com/ARMmbed/mbed-littlefs isn't even necessary, and one could directly flash the second partition and then `mbed_start_application()` from there, but is it possible to verify the checksum in that case?

**Comment by amq** [comment]
Actually, verifying the checksum without a filesystem should be possible with `flash.read()` and multi-fragment hashing described here https://github.com/ARMmbed/mbed-os-example-tls/tree/master/hashing

**Comment by c1728p9** [comment]
On almost all mbed-os devices, programming internal flash had a detrimental effect on interrupt latency. Because of this I would strongly discourage writing to internal flash while you have an active network connection, as this could cause many intermittent bugs.

**Comment by c1728p9** [comment]
Closing this question. Please re-open if you have further questions.
