### ISSUE TITLE
README.md needs update

### ISSUE THREAD

**Issue by chuanga** [ARMmbed/mbed-os-example-bootloader#66]
This is based upon review of (https://github.com/ARMmbed/mbed-os-example-bootloader/tree/mbed-os-5.9.0-oob).

1. In the "Building the bootloader" section, the update binary is no longer defined in the UPDATE_FILE macro, but rather in the mbed_app.json config file ("update_file" under config section). 

2. In the "Building the application with the bootloader" section, it did not specify the exact application to use, but the fact is that the sample bootloader is by default expecting blinky application to be used. We should just use blinky as the example application. Then should add a separate section explaining that if a different application is used, the "update_file" config should be changed when building the bootloader.

**Comment by AnotherButler** [comment]
@c1728p9

**Comment by c1728p9** [comment]
Hi @chuanga I created #70 to address these points. Since the bootloader example is not intended to be specific to mbed-os-example-blinky I left "Building the application with the bootloader" generic, but added extra clarification to it.

**Comment by 0xc0170** [comment]
@chuanga Is there anything needed for this issue to be resolved?

**Comment by c1728p9** [comment]
Closing this issue since it is resolved by #70. @chuanga if you have concerns feel free to reopen
