### ISSUE TITLE
Can't build in the online compiler

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/mbed-os-example-bootloader#67]
It is really unclear how to build with a bootloader in the online compiler.  

Using the steps in the readme adapted for the online compiler, users can compile the bootloader, but there is no clear way to add the bootloader binary into an application project.  

To recreate the issue:

1.  build the bootloader binary using the instructions here: https://github.com/ARMmbed/mbed-os-example-bootloader

2. import mbed-os-example-blinky.  Add a mbed_app.json file with these contents:

```
{
    "target_overrides": {
        "NUCLEO_F746ZG": {
            "target.bootloader_img": "my_bootloader.bin"
        }
    }
}
```

3. Add the bootloader binary to the application (mbed-os-example-blinky) project.  

Method 1 - fails.
When trying to *import...upload* the bootloader binary file (example file name "my_binary.bin") it says that it is an unsupported file type.  
![cant_upload_bin_file](https://user-images.githubusercontent.com/6129601/40941467-8b7c2f0c-6810-11e8-8048-2d5ed86fd76e.JPG)

Method 2 - reports fail, but actually works.  
When just dragging binary file into the project, it complains that the folder is not compatible with the online compiler.  
![freaks_out_on_bin_file](https://user-images.githubusercontent.com/6129601/40941496-9fdebdc0-6810-11e8-8119-0a26acfd179b.JPG)

After adding it the second way, it does seems to combine the bootloader binary with the application.

**Comment by maclobdell** [comment]
cc @thegecko

**Comment by adbridge** [comment]
@theotherjimmy Could you please comment on this also ?

**Comment by theotherjimmy** [comment]
@adbridge I'm already aware of this issue, and I have discussed it offline. Please don't see online compiler and assume that it's my bad.

**Comment by adbridge** [comment]
@theotherjimmy I was actually asking for a summary of the offline discussion to come into this issue so that it is visible and easy to find.

**Comment by theotherjimmy** [comment]
Ah, the result of the discussion is that we're working on removing those errors, especially because they're not really errors.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-614
