### ISSUE TITLE
Adding an application header

### ISSUE THREAD

**Issue by jonaskgandersson** [ARMmbed/mbed-os-example-bootloader#76]
In the bootloader tutorial in online documentation there is a section describing an application header, are there any example of implementation available?

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-1222

**Comment by SenRamakri** [comment]
@jonaskgandersson - I tried to look into this and was unable to find an example for application header/target.header_format as of now. We would look into making an example or updating the current example to capture that info. At this point I would suggest you to go ahead use the format as mentioned in the docs and let us know if you are seeing any issues with that and we can help with that. I will be closing this issue as of now and let us know if any issues with creating header_format.

**Comment by jonaskgandersson** [comment]
Thank you for your response!
I will give it a go.

**Comment by Essenceia** [comment]
Hello, sorry for re-opening the issue but where can I find the ``ARM Internal Ref: MBOTRIAGE-1222`` if I am not an ARM employee ?
