### ISSUE TITLE
Application Header Documentation

### ISSUE THREAD

**Issue by ghost** [ARMmbed/mbed-os-example-bootloader#88]
### Description
Latest mbed documentation contains references to an application header that can be generated (https://os.mbed.com/docs/latest/tutorials/bootloader.html). There is no documentation on how to use this functionality and the example does not contain any reference to this header functionality.

Specifically I am looking for: 

- Is there some sort of header struct that can be used to verify the header elements at runtime?
- There are 3 bin files generated for the main application when this is used. "[ProjectName]_application.bin", "[ProjectName]_update.bin", and "[ProjectName].bin". Which of these is the header included in? I assume _update.bin but there's no reference in the documentation.
- How are the header fields structured in mbed_lib.json. E.g ` ["magic", "const", "32be", "0x5a51b3d4"]`, What the fields in the previous array and how are they used?
- Is there any provision for including a signature of some kind (RSA, or other) for verification?

### Issue request type
[ X] Question  
[ ] Enhancement  
[ ] Bug

**Comment by theotherjimmy** [comment]
> Is there some sort of header struct that can be used to verify the header elements at runtime?

Not right now.

> There are 3 bin files generated for the main application when this is used. "[ProjectName]_application.bin", "[ProjectName]_update.bin", and "[ProjectName].bin". Which of these is the header included in? I assume _update.bin but there's no reference in the documentation

`[ProjectName].bin`. We should add `_update.bin` to the documentation. At the moment `_application.bin` and `_update.bin` are the same. When an update could be composed from something more than the application, this will change.

>What the fields in the previous array and how are they used?

https://os.mbed.com/docs/v5.10/tools/configuring-tools.html#target-header-format

>Is there any provision for including a signature of some kind (RSA, or other) for verification?

Not right now. We only have digests.

**Comment by ghost** [comment]
Thanks this helps!

**Comment by FabianInostroza** [comment]
> > Is there some sort of header struct that can be used to verify the header elements at runtime?
> 
> Not right now.
> 
> > There are 3 bin files generated for the main application when this is used. "[ProjectName]_application.bin", "[ProjectName]_update.bin", and "[ProjectName].bin". Which of these is the header included in? I assume _update.bin but there's no reference in the documentation
> 
> `[ProjectName].bin`. We should add `_update.bin` to the documentation. At the moment `_application.bin` and `_update.bin` are the same. When an update could be composed from something more than the application, this will change.
> 
> > What the fields in the previous array and how are they used?
> 
> https://os.mbed.com/docs/v5.10/tools/configuring-tools.html#target-header-format
> 
> > Is there any provision for including a signature of some kind (RSA, or other) for verification?
> 
> Not right now. We only have digests.

Is there a way to include the header in [ProjectName]_update.bin?
