### ISSUE TITLE
Support for STM32L4

### ISSUE THREAD

**Issue by cwq9999** [ARMmbed/mbed-os-example-bootloader#97]
### Description
According to this [application note](https://www.st.com/content/ccc/resource/technical/document/application_note/group0/6b/6d/66/98/7d/3e/46/cc/DM00282546/files/DM00282546.pdf/jcr:content/translations/en.DM00282546.pdf) from ST the F4 and L4 chips should be compatible with IAP-SD bootloading. Is it possible to add this feature for an L4 system and if so is is possible with only overrides in the .json files? 

### Issue request type

[ x] Question  
[ ] Enhancement  
[ ] Bug

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-404*

**Comment by c1728p9** [comment]
Hi @cwq9999, yeah you should be able to use the IAP-SD bootloader. If I understand the application note you linked to, you'll need to build the IAP-SD bootloader for your configuration. Then if you want to use Mbed's managed bootloader feature you'll need to pad out the IAP-SD bootloader binary up to the start of the user application (Padded to a size of 0xE000 according to the application note). Finally in your mbed-os application you'll need to specify the path to the IAP-SD bootloader in mbed_app.json:
```
{
    "target_overrides": {
        ...
        "<TARGET_NAME>": {
            "target.bootloader_img": "<path to padded IAP-SD bootloader binary>"
        },
        ...
}
```

More detailed information on building the application can be found in the [readme of this example](https://github.com/ARMmbed/mbed-os-example-bootloader#building-the-application-with-the-bootloader).

After you have done this you should be able to compile like normal to create the application. The build file `<project-name>.bin` can be used for direct drag-n-drop while the build file `<project-name>_application.bin` can be loaded by copying it onto the SD card.

**Comment by cwq9999** [comment]
Hi @c1728p9, that makes sense. Thank you for the clarification. That sounds great that this should be possible. The one item that isn't clear to me is if there is an override that is accessible for the padded size of 0xE000, or if I need to modify the mbed-os library itself. I noticed in the example that there is the override item (target.restrict_size": "0x20000") but I think that is only referring to the amount of space that will be allocated and not to the actual location. Any additional insight would be appreciated!

**Comment by cwq9999** [comment]
Hi @c1728p9 . I think I found the documentation needed. I believe this [link](https://os.mbed.com/docs/latest/tutorials/bootloader.html) answers that last question. Thanks for helping clarify what value I should change to. I will give this a try and see if I can get this to work.

**Comment by linlingao** [comment]
@cwq9999 It appears your question has been answered. We'll be closing this issue.
